paths:
  base_data_directory: "E:/dataset_test/ParquetToHuggingFace/data/raw_data"
  output_directory   : "E:/dataset_test/ParquetToHuggingFace/data/processed_data"

huggingface:
  repo_id            : "pr0mila-gh0sh/MediBeng"
  token_env_var      : "HUGGINGFACE_TOKEN"


